#create Custom Container Image
#Push to DockerHub Registry
---
- hosts: localhost
  tasks:
  - name: Pull .war artifact from Artifactory
   # become: true
    get_url:
      url:  http://35.192.12.219:8081/artifactory/libs-release/org/springframework/samples/spring-petclinic/2.0-SNAPSHOT/spring-petclinic-2.0-20201207.161559-2.war
      dest: /target
      url_username: admin
      url_password: vivek9060

  - name: Rename .war Artifact
    command: mv spring-petclinic-2.0-20201207.161559-2.war petclinic.war

  - name: Log into DockerHub
    docker_login:
      username: "9060"
      password: "vivek9060"

  - name: Pull Tomcat  Container Image
    docker_image:
      name: tomcat:8.0
      source: pull

  - name: Build image and with build args
    docker_image:
      name: petclinic
      build:
        path: /target
        pull: no
        args:
          listen_port: 8080
 
  - name: Push to docker hub
    docker_image:
      name: petclinic
      repository: 9060/petclinic:1.0
      push: yes
      source: local
